### ISSUE TITLE
Os endpoints devem continuar sendo em inglês?

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-api#10]
Acho que o título já descreve a dúvida kkkkkk mas complementando, como a gente é focado em CC@UFCG e quer incentivar a contribuição, talvez botar tudo PTBR seja uma ideia melhor... o que acham?

**Comment by JoseRenan** [comment]
Ping @thayannevls  @JuanBarros2

**Comment by danielmitre** [comment]
Eu gosto da ideia de usar APIs, de programar e principalmente de ler documentação em PT-br
:+1: 

[EDIT] Porém, algumas palavras podem causar um mal-entendido. Acho que rotas geralmente são um ponto fraco disso. Por exemplo:
* **/schedule/all** faz bastante sentido.
* **/horario/todos** faz parecer que vai retornar uma lista de TO-DO's.
* **/horario/all** funciona, mas é meio estranho.

**Comment by JuanBarros2** [comment]
Concordo com @danielmitre. Gosto da ultima abordagem e acredito que é possível estabelecer alguns padrões de código para manter a coerencia. Poderiamos adicionar um linter no repositório e colocar o travis pra rodar ele ao realizar um PR.

**Comment by JuanBarros2** [comment]
Só não gosto da segunda abordagem mesmo. É o grande problema da programação, sempre somos condicionados a escrever em inglês, mas quando o contexto pede português, tiltamos :smile:

**Comment by JoseRenan** [comment]
Assim, por padrão, no REST os recursos tem de estar no plural e o / retornar todos, daí ao invés de `/horarios/all` ficaria só `/horarios` então nn seria muito problema

**Comment by thayannevls** [comment]
Concordo! Tudo ptbr
