### ISSUE TITLE
Renomear endpoints para PTBR

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-api#13]
Renomear todos os endpoints e parametros para PTBR.

`/v1/repositories` vira `/v1/repositorios`
`/v1/subjects` vira `/v1/disciplinas`

**Comment by jadsonluan** [comment]
Os nomes das variáveis/arquivos também devem ser renomeados?
`import subjRouter from './subjects/subj-controller';` de /v1/index.js para 
`import disciplinaRouter from './disciplinas/subj-controller';`

**Comment by thayannevls** [comment]
@jadsonluan No caso, faltou renomear o arquivo no final também

`import disciplinaRouter from './disciplinas/disciplina-controller';`

**Comment by jadsonluan** [comment]
disciplina-controller ou disciplinas-controller? Como atualmente tá subj não dá pra saber se é singular ou plural.

**Comment by thayannevls** [comment]
@JoseRenan pode dizer melhor

**Comment by JoseRenan** [comment]
Acho que disciplinas msm pra sehuir a mesma estrutura do REST

**Comment by jadsonluan** [comment]
Show. Fiz o PR com as mudanças e acrescentei a atualização da documentação, só não traduzi os query param porque não sabia se devia, @JoseRenan @thayannevls

**Comment by thayannevls** [comment]
@jadsonluan @JoseRenan adaptei as endpoints para as que luan mudou aqui opendevufcg/issueai#63

Se quiserem podem merjar a pr
