### ISSUE TITLE
Adicionar filtragem no endpoint de disciplinas

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-api#14]
Filtragem por período, por categoria, quantidade de créditos (?) no endpoint de disciplinas de CC na PPC 2017.

Por exemplo: `/v1/subjects?category=obrigatoria` listaria apenas as disciplinas obrigatórias

**Comment by thayannevls** [comment]
Devido a reformulação do laguinho #31, vou fechar a issue
