### ISSUE TITLE
Adicionar MongoDB como BD

### ISSUE THREAD

**Issue by juliobguedes** [OpenDevUFCG/laguinho-api#17]
Por enquanto ainda estamos mantendo nossos dados em arquivo(s) local(is) do repositório. Entretanto, adicionar o Mongo no laguinho é uma possibilidade enorme de aprendizado pra nós aprendermos e incentivarmos o uso de novas tecnologias. Além disso, o mongo tem um limite gratuito de 512MB de dados, então creio que é um limite interessante e que pode ser mais que suficiente pros nossos projetos.

Por isso, estou criando essa issue para discutirmos a viabilidade de adicionar (e o processo de adição, caso seja aceito) do uso de mongoDB pros nossos dados.

**Comment by JoseRenan** [comment]
@juliobguedes, uma discussão que foi levantada foi sobre como fazer isso de forma que o laguinho se mantesse colaborativo, se esse seria um dos focos do laguinho, manter ele de forma que qualquer um pudesse contribuir pro laguinho usando o fluxo git de contribuição, ou se seria ok ter essa contribuição de outras formas... tbm teríamos de ver se pensarmos em otura forma de colaboração, como faríamos pra manter os dados sendo revisados por um humano antes de serem oficialmente inseridos... acho que essas duas coisas podem ser discutidas nessa issue msm, e acho tbm que vale levar em consideração a issue #21 pra fazer esse tipo de coisa, tipo, vc teria de criar uma conta de desenvolvimento pra poder contribuir com dados (seria a mesma coisa de precisar ter uma conta no github pra contribuir com dados)

**Comment by thayannevls** [comment]
Sim, seria muito legal ter isso. Poderíamos fazer com que o banco se alimentasse com *csv* ou já o formato que temos agora pra manter contribuivel.

Porém assim como na outra issue, eu acho essas discussões cedo demais para o laguinho que ainda é muito imaturo e não tem nenhuma endpoint que não seja relacionada ao IssueAI. Eu acho que valha mais a pena investir em outras discussões por agora...

**Comment by thayannevls** [comment]
Devido a reformulação do laguinho #31, vou fechar a issue
