### ISSUE TITLE
Refactor: Github.js

### ISSUE THREAD

**Issue by juliobguedes** [OpenDevUFCG/laguinho-api#18]
Atualmente, o arquivo `src/v1/repositories/github.js` está altamente acoplado à query de recuperar dados do repositório. Como a api do GitHub será utilizada em outras queries, é interessante refatorar esse arquivo, removendo tudo que pertence à query de informações dos repositórios, e mover para `/lib`.

**Comment by thayannevls** [comment]
@JoseRenan

**Comment by thayannevls** [comment]
Devido a reformulação do laguinho #31, vou fechar a issue
