### ISSUE TITLE
Criar endpoint que retorne contribuidores de projetos open source da UFCG

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/laguinho-api#2]
O [IssueAi](https://github.com/OpenDevUFCG/IssueAi) precisa de uma endpoint que retorne todos os colaboradores dos projetos Open Source da UFCG, contendo as informações:

- Nome
- Usuário
- Link pro github
- Avatar

**Comment by thayannevls** [comment]
@JoseRenan Posso começar essa task?

**Comment by JoseRenan** [comment]
@thayannevls, se joga no laguinho e vem virar xmen :muscle:

**Comment by JuanBarros2** [comment]
Pessoal, criem um taskboard pra esse projeto. Queria ajudar tbm :smile:

**Comment by thayannevls** [comment]
Devido a reformulação do laguinho #31, vou fechar a issue
