### ISSUE TITLE
Onde devo botar meus dados no laguinho-api?

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/laguinho-api#22]
Se eu tenho um dado, como devo colocá-lo no laguinho? E em que formato? Quais são as regras?

**Comment by JoseRenan** [comment]
A gente deveria padronizar o formato de arquivos que colocamos aqui? se sim, tu acha que o melhor seria fechar tudo com CSV?

**Comment by JoseRenan** [comment]
Uma discussão que ficou em aberto no #23 (e seria bom trazer pra cá) sobre onde colocar foi sobre criar um repositório pra colocar os dados e aqui ficarmos linkando pra esse repositório de dados, talvez fosse uma boa a gente discutir uma estrutura de diretórios pra botar os dados ao invés de colocar na pasta do código das rotas, colocar em um /data no root msm

**Comment by thayannevls** [comment]
Resolvido aqui https://github.com/OpenDevUFCG/laguinho-api/issues/31#issuecomment-517514522
