### ISSUE TITLE
Adicionar endpoint para dependências de disciplinas

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/laguinho-api#24]
O [roadmap](https://github.com/OpenDevUFCG/roadmap-cc) está realizando um tratamento em cima dos [dados das disciplinas](https://github.com/OpenDevUFCG/roadmap-cc/blob/development/data/disciplinas-ppc-2017.csv) para transformar as linhas em registros a qual uma coluna será o id da disciplina e outra seria um id de outra disciplina que é pre requisito da primeira. O script tenta solucionar o problema de ter vários pre requisitos em uma disciplina e a solução empregada foi criar um registro para cada relacionamento entre disciplina. 

Pensando nisso, acho que seria possível adicionar uma endpoint junto às existentes sobre `subject` para retornar agora os [valores já tratados](https://github.com/OpenDevUFCG/roadmap-cc/blob/development/data/relacionamentos-disciplinas-ppc2017.csv) pelo roadmap.

O processo seria bem semelhante com [o que já é feito para obter as disciplinas](https://github.com/OpenDevUFCG/laguinho-api/blob/master/src/v1/subjects/subj-controller.js) e poderia gerar dados importantes para quem desejasse utilizar.

**Comment by lucasmedeiros** [comment]
@JuanBarros2 Isso não já foi implementado por @fanny em alguma PR anterior?

Acho que o que tá descrito nessa issue foi implementado [nesse link](https://github.com/OpenDevUFCG/laguinho-api/blob/master/src/v1/subjects/subj-controller.js).

**Comment by thayannevls** [comment]
Devido a reformulação do laguinho #31, vou fechar a issue
