### ISSUE TITLE
Teste de endpoint

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/laguinho-api#26]
Galera seria legal colocar alguma ferramenta de fazer teste de endpoint. Acho que se crescer a quantidade de endpoint seja meio problemático ficar verificando isso sem uma ferramenta que teste automaticamente pra gente.

**Comment by JoseRenan** [comment]
Top, conheço essa ferramenta: https://www.frisbyjs.com/ muito boa pra teste de API REST tu tem alguma outra sugestão?

**Comment by JuanBarros2** [comment]
Não conheço nenhuma

**Comment by JuanBarros2** [comment]
Teria como a gente rodar um travis com esses testes @JoseRenan ?

**Comment by JoseRenan** [comment]
> Teria como a gente rodar um travis com esses testes @JoseRenan ?

Eita, isso é um problema, acho que com frisby a API temd e estar rodando :thinking: eu nunca configurei ele com travis nn, mas ainda assim, acho que outras opções também precisariam dele rodando se quisesse testar os endpoints diretamente... e não faz sentido fazer testes com mock do endpoint (pq a gente quer testar O ENDPOINT) :thinking: :thinking:

**Comment by JoseRenan** [comment]
[nesse post](https://medium.com/@hdeodato/teste-autom%C3%A1tico-de-api-rest-usando-com-node-js-mocha-chai-6aec4613d100) ele mostra como configurar com mocha e chai, mas ainda assim ele seta uma URL de um servidor rodando tbm

**Comment by JuanBarros2** [comment]
Lá no Analytics a gente consegue rodar no Gitlab. Será que não conseguimos configurar para fazer isso?

**Comment by JoseRenan** [comment]
A gente pode ver se funciona, o caminho feliz seria dar um `npm start && npm test`

**Comment by thayannevls** [comment]
Devido a reformulação do laguinho #31, vou fechar a issue
