### ISSUE TITLE
Estrutura do docs poderia ser diferente

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/laguinho-api#3]
O [docs](https://github.com/OpenDevUFCG/laguinho-api/tree/master/docs) atualmente tem uma estrutura que todos os endpoints ficam dentro do README.md certo?

Quando formos adicionando mais endpoints ficará confuso, não era melhor adotar uma estrutura separada por pastas? E no README.md ter apenas um sumário de endpoints existentes

**Comment by JoseRenan** [comment]
Concordo, ainda estou fazendo melhorias na documentação pra facilitar a contribuição, acrescentarei isso no PR tbm

**Comment by JoseRenan** [comment]
Concordo, acho que poderíamos adicionar um novo arquivo .md pra cada rota (e suas sub-rotas) e deixar no README um índice com links para todas elas. Será que tem algum problema estar todos na raiz da pasta docs, @thayannevls?

**Comment by thayannevls** [comment]
@JoseRenan acho que as pastas poderiam representar os "módulos" da api. Repositórios, glossario, disciplinas.... e em cada módulo teria endpoints relacionando aquela entidade. Faz sentido?

**Comment by JoseRenan** [comment]
Mas é que eu acho que 1 arquivo seria suficiente pra especificar cada "módulo", daí não precisaria de pastas, pelo menos não pra por 1 arquivo só :thinking:

**Comment by thayannevls** [comment]
Pensei em tipo, Repositórios n poderia ter outras endpoints?
