### ISSUE TITLE
Reestruturação do projeto

### ISSUE THREAD

**Issue by paulojbleitao** [OpenDevUFCG/laguinho-api#34]
A api precisa ser reconfigurada, agora em Python 3 e utilizando [flask](https://palletsprojects.com/p/flask/) e [pipenv](https://github.com/pypa/pipenv). É importante notar que isso precisa ser feito em uma branch separada, para não quebrar a api atual (mesmo considerando que será substituída no futuro).

Aceito sugestões de estruturas de diretórios, pois não manjo xd

**Comment by JoseRenan** [comment]
@paulojbleitao, tem a estrutura do caboabanana (apesar de closed source, Tu tem acesso KKKKKK) Acho que tá bem padronizada. Na doc do flask tem algumas sugestões também

**Comment by lucasmedeiros** [comment]
@JoseRenan Show de bola, vou dar uma olhada
