### ISSUE TITLE
Adicionar documentação de como executar o laguinho-api

### ISSUE THREAD

**Issue by lucasaarcoverde** [OpenDevUFCG/laguinho-api#42]
Ia tentar rodar o laguinho na branch development, mas ta sem a descrição de como executar no README

**Comment by JoseRenan** [comment]
Tu queres fazer???

**Comment by lucasaarcoverde** [comment]
Quero, como faz?

**Comment by JoseRenan** [comment]
Pra rodar, tu tem de fazer a instalação do pipenv como fez no [laguinho](https://github.com/OpenDevUFCG/laguinho), rodar `pipenv install --dev` e `pipenv run start`, daí ele vai logar dizendo que tá rodando na porta 8080
