### ISSUE TITLE
Adicionar endpoit para publicar datasets

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-api#43]
Como foi definido em reunião aberta, continuando a discussão do #31, precisamos de um endpoint que publicará um JSON com [metadados do dataset (definidos no laguinho.json)](https://github.com/OpenDevUFCG/laguinho/issues/13).

O endpoint poderia ser um POST no `/datasets`.

OBS: Foi definido na mesma reunião que, pra um MVP, armazenaríamos essa informação em um array em memória msm, ao invés de usar algum BD

**Comment by lucasaarcoverde** [comment]
Posso fazer?

**Comment by JoseRenan** [comment]
Parece que @jessescn tem um concorrente

**Comment by JoseRenan** [comment]
A princípio, podemos só dar append do JSON num array, sem nenhuma lógica extra, a meta é conseguir que a CLI tenha um back pra fazer publish e get rápido, é daí pra frente os dois poderem caminhar mais independentemente
