### ISSUE TITLE
Nome de dataset deve ser único

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-api#47]
Atualmente, está sendo possível salvar mais de um dataset com o mesmo nome no `POST /datasets`, seria bom termos algum tipo de validação que verifique se o nome do dataset já existe e retornassemos um `409` indicando que aquele dataset já foi salvo

**Comment by JoseRenan** [comment]
Acho que faz sentido verificar se a tupla (URL, Path) é única também, visto que mesmo que repos com nomes diferentes, se tiver algum outro com o mesmo URL e Path, ele ja foi publicado, faz sentido???

**Comment by paulojbleitao** [comment]
> Acho que faz sentido verificar se a tupla (URL, Path) é única também, visto que mesmo que repos com nomes diferentes, se tiver algum outro com o mesmo URL e Path, ele ja foi publicado, faz sentido???

Eu concordo, não faz sentido ter isso duplicado mesmo

Eu posso fazer essa :slightly_smiling_face:
