### ISSUE TITLE
Recuperar dataset por nome

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-api#48]
Implementar um endpoint `GET /datasets/:nomedodataset` que retorne o JSON com os metadados salvos do dataset

**Comment by lucasaarcoverde** [comment]
Oii, posso fazer?

**Comment by JoseRenan** [comment]
@lucasmedeiros te dei assign, não dei de @grabowski74 porque ele nn aparece na lista (só aparece admins e pessoas que comentaram a issue)

**Comment by matheusarauj** [comment]
poxa, queria assign
