### ISSUE TITLE
Criar um container Docker para o laguinho

### ISSUE THREAD

**Issue by paulojbleitao** [OpenDevUFCG/laguinho-api#49]
É interessante que exista um container para a API, pois facilita rodar o projeto, principalmente para o desenvolvimento da [CLI](https://github.com/OpenDevUFCG/laguinho).

É importante também documentar como executar o container (dependências, comandos na cli mesmo e tal).

Mais detalhes são com @JoseRenan porque ele que entende dessas coisas :slightly_smiling_face:

**Comment by lucasaarcoverde** [comment]
Oii, posso fazer essa?

**Comment by paulojbleitao** [comment]
Vai em frente 🤙

**Comment by felipemarinho97** [comment]
Oi, como está o andamento dessa issue? queria fazer

**Comment by lucasmedeiros** [comment]
@JoseRenan @lucasaarcoverde Se estiverem muito atarefados, eu posso transferir a issue pra @felipemarinho97 sem problemas, o que acham?

**Comment by JoseRenan** [comment]
@lucasaarcoverde disse que não tá trabalhando nela, pode passar!!!

**Comment by lucasmedeiros** [comment]
@felipemarinho97 Te dei o assign! :smile:
