### ISSUE TITLE
Adicionar endpoint que retorne as cadeiras de CC e seus detalhes

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/laguinho-api#5]
Gostaria de adicionar uma endpoint para retornar as disciplinas e seus respectivos detalhes. Disponho um CSV com informações sobre nome, ID, dependência, obrigatoriedade, numero de vagas (média) e gostaria de adiciona-las ao repositório.

**Comment by thayannevls** [comment]
@JoseRenan Poderia mandar o link daquele site que você citou pra colocar os csv e ser colaborativo? Era bom pra avaliarmos em usar aqui

**Comment by thayannevls** [comment]
@JuanBarros2 Dei uma procurada e acabei [achando](https://app.workbenchdata.com/workflows/7924/)


Tem como submeter o CSV e organizar lá, quer tentar?

**Comment by JoseRenan** [comment]
Revendo ele agora, não encontrei como colaborar com os dados, mas dá pra colaborar com o workflow de scrapping, eu acho :thinking:

**Comment by thayannevls** [comment]
Existem vários workflows que se pode escolher, cria um e veja as opções, pode ser por drive, link, upload, tweet, join de outro workflow...

**Comment by JuanBarros2** [comment]
Acho que seria melhor o CSV mesmo. É difícil ter controle do que entra nesses workflows e o PR é uma ótima maneira de garantir a coerencia dos dados. Se a questão for espaço, posso jogar o CSV para o repositório raiz e controlarei os dados por PR por lá mesmo.
