### ISSUE TITLE
Definir e configurar o banco de dados

### ISSUE THREAD

**Issue by lucasmedeiros** [OpenDevUFCG/laguinho-api#53]
Atualmente, estamos utilizando um array para armazenamento dos dados no servidor, tornando-o `stateful`, como era previsto para o primeiro MVP. Mas, precisamos definir um banco de dados, e configurá-lo.

**Próximos passos**:
- [x] Definir o banco de dados (forte candidato: MongoDB).
- [ ] Integrá-lo com a nossa API `flask`.

**Comment by matheusarauj** [comment]
Posso pegar essa task?

**Comment by lucasmedeiros** [comment]
Assignado ;)

**Comment by JoseRenan** [comment]
Pra facilitar a configuração local dos contribuidores, seria bom ter um docker-compose com o BD pra subir, pra não precisar instalar mongo localmente ou vir a ter problemas com alguma configuração do mongo que o contribuidor já tenha

**Comment by JoseRenan** [comment]
@lucasmedeiros, acredito que melhor não hospedarmos agora, deixar apenas local mesmo, acho não cabe por isso numa issue, já que é uma task mais dos maintainers mesmo, quando a gente for hospedar o laguinho todo

**Comment by lucasmedeiros** [comment]
@JoseRenan não tenho experiência alguma com Docker, mas posso dar uma olhada em breve. E concordo com você quanto a deixar local no momento, removi das "tasks" da issue.

**Comment by JoseRenan** [comment]
Posso dar uma ajuda com isso, avisa no discord quando for fazer

**Comment by lucasmedeiros** [comment]
Top, fala com @grabowski74 tbm

**Comment by paulojbleitao** [comment]
Como está o andamento dessa issue? @juliobguedes mostrou interesse nela

**Comment by JoseRenan** [comment]
Eu vou criar o docker-compose com o mongo e uma interfacezinha pra administrar e commito

**Comment by JoseRenan** [comment]
Tá na PR #67 @juliobguedes assim que merjada, já podemos começar a trabalhar na migração
