### ISSUE TITLE
Hall de contribuição

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/laguinho-api#7]
Vocês acham que daria pra adicionar o hall da contribuição igual o do @OpenDevUFCG/tamburetei ?

**Comment by JoseRenan** [comment]
Dá sim, usa [isso aqui](https://github.com/sourcerer-io/hall-of-fame) no @OpenDevUFCG/tamburetei e no @OpenDevUFCG/issueai

**Comment by JuanBarros2** [comment]
@JoseRenan tentei seguir o tutorial dele, mas não consigo encontrar o laguinho na lista de repositórios que faço parte
