### ISSUE TITLE
Adicionar topicos e contador de bytes por linguagens em /v1/repositories

### ISSUE THREAD

**Issue by danielmitre** [OpenDevUFCG/laguinho-api#9]
Pode ser interessante retornar as [linguagens](https://developer.github.com/v3/repos/#list-languages) e os [tópicos](https://developer.github.com/v3/repos/#list-all-topics-for-a-repository) de cada repositório.

A ideia desses imediatamente seria poder filtrar melhor os repositórios para um usuário que busca uma oportunidade de contribuir.

[Contribuições por usuário](https://developer.github.com/v3/repos/#list-contributors) também seriam úteis para fazer um sistema (no estilo do [Tambureteiros](https://github.com/OpenDevUFCG/Tamburetei#tambureteiros)) de ranking geral entre todos os repositórios listados pelo laguinho.

**Comment by JuanBarros2** [comment]
Boa!! Acho que o pessoal do @OpenDevUFCG/issueai tava planejando desenvolver filtros pra ajudar a quem quiser contribuir. Acho que um filtro de linguagem seria muito bom

**Comment by JoseRenan** [comment]
O github disponibiliza na API a lista de linguagens que o repositório tem, poderia adicionar isso na query que estamos fazendo pra API deles.

**Comment by JoseRenan** [comment]
> [Contribuições por usuário](https://developer.github.com/v3/repos/#list-contributors) também seriam úteis para fazer um sistema (no estilo do [Tambureteiros](https://github.com/OpenDevUFCG/Tamburetei#tambureteiros)) de ranking geral entre todos os repositórios listados pelo laguinho.

@thayannevls tá implementando esse endpoint eu acho no #2

**Comment by JoseRenan** [comment]
> O github disponibiliza na API a lista de linguagens que o repositório tem, poderia adicionar isso na query que estamos fazendo pra API deles.

Quer pegar o assign dessa task @danielmitre 😄 ❤️ KKKKK

**Comment by danielmitre** [comment]
Estarei ocupado por alguns dias. Se quando eu terminar um trabalho essa task estiver livre eu venho buscar, @JoseRenan

**Comment by JoseRenan** [comment]
Beleza!!!

**Comment by lucasmedeiros** [comment]
Fechando issue por conta da reformulação do laguinho.

Ver #31

**Comment by lucasmedeiros** [comment]
Fechando issue por conta da reformulação do laguinho.

Ver #31
